### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by fgblomqvist** [SCUEvals/scuevals-api#10]
View details in Rollbar: [https://rollbar.com/scuevals-api/scuevals-api/items/9/](https://rollbar.com/scuevals-api/scuevals-api/items/9/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/framework_flask.py", line 108, in _nr_wrapper_Flask_handle_exception_
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/framework_flask.py", line 45, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 40, in wrapper
    return fn(*args, **kwargs)
  File "/app/scuevals_api/roles.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/app/scuevals_api/resources/professors.py", line 56, in get
    for ev in professor.evaluations
  File "/app/scuevals_api/resources/professors.py", line 56, in <listcomp>
    for ev in professor.evaluations
  File "/app/scuevals_api/models/evaluation.py", line 36, in user_vote
    vote = Vote.query.filter(Vote.student_id == user.id, Vote.evaluation_id == self.id).one_or_none()
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by fgblomqvist** [comment]
This was caused by a deleted account (something that will never happen in the future again).
