### ISSUE TITLE
DB error on posting of duplicate eval

### ISSUE THREAD

**Issue by fgblomqvist** [SCUEvals/scuevals-api#11]
View details in Rollbar: [https://rollbar.com/scuevals-api/scuevals-api/items/11/](https://rollbar.com/scuevals-api/scuevals-api/items/11/)

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/framework_flask.py", line 45, in _nr_wrapper_handler_
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 40, in wrapper
    return fn(*args, **kwargs)
  File "/app/scuevals_api/roles.py", line 30, in wrapper
    return fn(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/webargs/core.py", line 445, in wrapper
    return func(*new_args, **kwargs)
  File "/app/scuevals_api/resources/evaluations.py", line 61, in post
    db.session.commit()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/database_psycopg2.py", line 35, in execute
    **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/database_dbapi2.py", line 25, in execute
    *args, **kwargs)
IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "uq_evaluations_student_id"
DETAIL:  Key (student_id, professor_id, section_id)=(11, 9, 2) already exists.
 [SQL: 'INSERT INTO evaluations (version, data, student_id, professor_id, section_id) VALUES (%(version)s, %(data)s, %(student_id)s, %(professor_id)s, %(section_id)s) RETURNING evaluations.id'] [parameters: {'version': 1, 'data': '{"attitude": 1, "grading_speed": 1, "comment": "lol2", "clarity": 1, "recommended": 1, "workload": 1, "difficulty": 1, "availability": 1, "resourcefulness": 1}', 'student_id': 11, 'professor_id': 9, 'section_id': 2}]Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/database_psycopg2.py", line 35, in execute
    **kwargs)
  File "/app/.heroku/python/lib/python3.6/site-packages/newrelic/hooks/database_dbapi2.py", line 25, in execute
    *args, **kwargs)
IntegrityError: duplicate key value violates unique constraint "uq_evaluations_student_id"
DETAIL:  Key (student_id, professor_id, section_id)=(11, 9, 2) already exists.

```

**Comment by fgblomqvist** [comment]
Fixed in d80d646f14a3865060cc7ac80aa1f0025950b5fe.
